
spring:
  application:    
  cloud:    
    gateway:
      routes:
        - id: to-theater-getAll
          uri: lb://theater-service
          predicates:
            - Path=/theater
            - Method=GET
          filters:
#            - RewritePath=/reservation, /reservation   
        - id: to-theater-add
          uri: lb://theater-service
          predicates:
            - Path=/theater
            - Method=POST
          filters:
#            - RewritePath=/reservation, /reservation       
      discovery:
        locator:
          enabled: true