spring:
  application:    
  cloud:    
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping : true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PATCH
            - PUT        
            allowedHeaders:
            - Content-Type  
            - X-Requested-With 
            - Origin
            - Accept
            - Authorization
            exposedHeaders:
            - Authorization        
           

      routes:
        - id: to-theater-getAll
          uri: lb://theater-service
          predicates:
            - Path=/theater
            - Method=GET
          filters:
#            - RewritePath=/reservation, /reservation   
        - id: to-theater-add
          uri: lb://theater-service
          predicates:
            - Path=/theater
            - Method=POST

        - id: to-theater-getOne
          uri: lb://theater-service
          predicates:
            - Path=/theater/one
            - Method=GET
          filters:
#            - RewritePath=/reservation, /reservation    
        - id: to-movieRomm-add
          uri: lb://theater-service
          predicates:
            - Path=/movieRoom
            - Method=POST
        - id: to-movieRomm-getOne
          uri: lb://theater-service
          predicates:
            - Path=/movieRoom/one
            - Method=GET      
      discovery:
        locator:
          enabled: true