server:
  port: 8282 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TheaterDB
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop